name: Deploy to Vercel

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # Step 3: Use Node.js 22
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 5: Run pre-build checks
      - name: Run pre-build checks
        run: pnpm pre-build

      # Step 6: Build the project
      - name: Build the project
        run: pnpm build

      # Step 7: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Step 8: Deploy to Vercel
      - name: Deploy to Vercel
        run: npx vercel deploy --prod --prebuilt --token ${{ secrets.VERCEL_TOKEN }} --yes
